### ISSUE TITLE
License

### ISSUE THREAD

**Issue by drrb** [jbclements/rust-antlr#1]
I'd like to include your ANTLR grammar in a NetBeans plugin that I'm creating, and would like to attribute the grammar to you.

Is the grammar currently available under an open source license? If not, would you mind making it so? I plan to license the plugin under [GPLv3](http://www.gnu.org/licenses/gpl-3.0.html), so [any compatible license](http://www.gnu.org/licenses/license-list.html#GPLCompatibleLicenses) on your part would work for me. Specifically, I'd be most happy with GPLv3 or [Apache 2](http://www.apache.org/licenses/LICENSE-2.0.html).

Thanks!

**Comment by jbclements** [comment]
Oops, missed this. It's now apache 2. And it only took me two^H^H^Hthree years!
