### ISSUE TITLE
Moving grammar to official ANTLR 4 grammars repository

### ISSUE THREAD

**Issue by KvanTTT** [jbclements/rust-antlr#2]
Do you want to move your grammar to [official repository](https://github.com/antlr/grammars-v4)? Could you please add licence (something like BSD or MIT)?

**Comment by jbclements** [comment]
I think this grammar is extremely out of date.

HOWEVER, I'm also absolutely delighted to license it. The work is now licensed under the Apache License, version 2.0, and my latest push should make this clear.

Thanks for your interest!
